<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.PagueAres.Domain\Ares.PagueAres.Domain.csproj" />
    <ProjectReference Include="..\Ares.PagueAres.Infrastructure\Ares.PagueAres.Infrastructure.csproj" />
  </ItemGroup>

</Project>
